<!DOCTYPE html>
<html>
    <?php
        $songMap = [
        "001" => [ "file" => "001.mp3", "title" => "Mis (Alex G)" ],
        "002" => [ "file" => "002.mp3", "title" => "All Too Well (Taylor Swift)" ],
        "003" => [ "file" => "003.mp3", "title" => "Misunderstanding (D-Train)" ],
        "013" => [ "file" => "013.mp3", "title" => "Multo (Cup of Joe)" ],
        "010" => [ "file" => "010.mp3", "title" => "Nero Forte (Slipknot)" ],
        "064" => [ "file" => "064.mp3", "title" => "Young & Dumb (Cigarettes After Sex)" ],
        "067" => [ "file" => "067.mp3", "title" => "Cpr (cupcakKe)" ],
        "069" => [ "file" => "069.mp3", "title" => "Careless Whisper (George Micheal)" ],
        "111" => [ "file" => "111.mp3", "title" => "Golden (HUNTR/X, EJAE, AUDREY NUNA, REI AMI)" ],
        "123" => [ "file" => "123.mp3", "title" => "Folded (Kehlani)" ],
        "130" => [ "file" => "130.mp3", "title" => "No Longer You (Jorge Rimera-Herrans)" ],
        "202" => [ "file" => "202.mp3", "title" => "More Than A Woman (Bee Gees)" ],
        "222" => [ "file" => "222.mp3", "title" => "Eternity (Alex Warren)" ],
        "237" => [ "file" => "237.mp3", "title" => "HAZARD DUTY PAY! (JPEGMAFIA)" ],
        "301" => [ "file" => "301.mp3", "title" => "She Knows (Ne-yo)" ],
        "303" => [ "file" => "303.mp3", "title" => "Kingston (Faye Webster)" ],
        "306" => [ "file" => "306.mp3", "title" => "Given Up (Linkin Park)" ],
        "315" => [ "file" => "315.mp3", "title" => "I Don't Like (Chief Keef)" ],
        "316" => [ "file" => "316.mp3", "title" => "BOOMBAYAH (BLACKPINK)" ],
        "334" => [ "file" => "334.mp3", "title" => "Slow Down (Chase Atlantic)" ],
        "369" => [ "file" => "369.mp3", "title" => "Last Resort (Papa Roach)" ],
        "388" => [ "file" => "388.mp3", "title" => "Placing the Blame (Self)" ],
        "420" => [ "file" => "420.mp3", "title" => "Rodeo (Lah Pat, Flo Milli)" ],
        "431" => [ "file" => "431.mp3", "title" => "Japanese Denim (Daniel Caesar)" ],
        "435" => [ "file" => "435.mp3", "title" => "435 (Tyler, the Creator)" ],
        "444" => [ "file" => "444.mp3", "title" => "OMG (NewJeans)" ],
        "456" => [ "file" => "456.mp3", "title" => "Mingle Game Song (Squid Game Original Soundtrack)" ],
        "468" => [ "file" => "468.mp3", "title" => "Buddy Holly (Weezer)" ],
        "505" => [ "file" => "505.mp3", "title" => "505 (Arctic Monkeys)" ],
        "525" => [ "file" => "525.mp3", "title" => "Old Love(Yuji)" ],
        "555" => [ "file" => "555.mp3", "title" => "Psychosocial (Slipknot)" ],
        "600" => [ "file" => "600.mp3", "title" => "Storm (Jorge Rivera-Herrans)" ],
        "607" => [ "file" => "607.mp3", "title" => "Blue (Yung Kai)" ],
        "611" => [ "file" => "611.mp3", "title" => "Ghost (Justin Bieber)"],
        "628" => [ "file" => "628.mp3", "title" => "Right Side of My Neck (Faye Webster)" ],
        "665" => [ "file" => "665.mp3", "title" => "Scheweinehund (Kreiml & Samurai)" ],
        "666" => [ "file" => "666.mp3", "title" => "CHERRY BOMB (Tyler, the Creator)" ],
        "667" => [ "file" => "667.mp3", "title" => "Ballin' (Roddy Ricch)" ],
        "696" => [ "file" => "696.mp3", "title" => "It's Cold Out Here (Modern Baseball)" ],
        "772" => [ "file" => "772.mp3", "title" => "ALL CAPS (Madvillain, Madlib, MF DOOM)" ],
        "777" => [ "file" => "777.mp3", "title" => "Naiilang (Le John)" ],
        "800" => [ "file" => "800.mp3", "title" => "1-800 (bbno$)" ],
        "900" => [ "file" => "900.mp3", "title" => "F.U.C.K (Victoria Monet)" ],
        "911" => [ "file" => "911.mp3", "title" => "911/Mr. Lonely (Tyler, the Creator)" ],
        "932" => [ "file" => "932.mp3", "title" => "In Moonlight (Jerry Cantrell)" ]
        ];
    ?>
</html>